# Animations
animations = 1
layer_animations = 1

# Windows
border_radius = 16
borderpx = 2
bordercolor = 0xAAAAAAFF
focuscolor = 0xFFFFFFFF

# Layout
gappih = 4
gappiv = 0
gappoh = 0
gappov = 0

# Blur
blur = 1
blur_optimized = 0
blur_params_radius = 3
blur_params_num_passes = 1
blur_layer = 1
focused_opacity = 0.9
unfocused_opacity = 0.8

# Cursor
cursor_size = 20
cursor_theme = Adwaita
