# App keybinds
bind = SUPER, t, spawn, kitty

# Noctalia keybinds
bind = SUPER, space, spawn, noctalia msg panel-toggle launcher
bind = SUPER+SHIFT, s, spawn, noctalia msg screenshot-region
bind = NONE, Print, spawn, noctalia msg screenshot-region
bind = SUPER, c, spawn, noctalia msg panel-toggle control-center

# MangoWM
bind = SUPER, r, reload_config
bind = SUPER, X, killclient
bind = SUPER, y, togglefloating
bind = SUPER, Left, viewtoleft
bind = SUPER, Right, viewtoright
bind = SUPER+SHIFT, Left, move_client, left
bind = SUPER+SHIFT, Right, move_client, right
bind = SUPER+SHIFT, Up, move_client, up
bind = SUPER+SHIFT, Down, move_client, down
bind = SUPER, Tab, enteroverview
bind = SUPER+CTRL, Left, tagtoleft, synctag:1
bind = SUPER+CTRL, Right, tagtoright, synctag:1

# Function keys (i copied this from the mangowm docs)
; Brightness
bind = NONE,XF86MonBrightnessUp, spawn, brightnessctl s +2%
bind = NONE,XF86MonBrightnessDown, spawn, brightnessctl s 2%-
; Volume
bind = NONE, XF86AudioRaiseVolume, spawn, wpctl set-volume @DEFAULT_SINK@ 5%+
bind = NONE, XF86AudioLowerVolume, spawn, wpctl set-volume @DEFAULT_SINK@ 5%-
bind = NONE, XF86AudioMute ,spawn, wpctl set-mute @DEFAULT_SINK@ toggle
bind = SHIFT, XF86AudioMute, spawn, wpctl set-mute @DEFAULT_SOURCE@ toggle
